version: "3.9"

services:
  schedule_manager-be:
    container_name: schedule_manager-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/django
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "schedule_manager"
      POSTGRES_PASSWORD: "postgres"
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - schedule_manager-be
    restart: always

volumes:
  postgres_data:
